version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - echo "Dependencies installed successfully..."

  pre_build:
    commands:
      - echo "Pre-build steps.."

  build:
    commands:
      - echo "Build started"
      - python setup.py install
      - echo "Build completed"

  post_build:
    commands:
      - echo "Running tests"
      - pytest
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_USERNAME/python_app:v3" .
      - docker push "$DOCKER_REGISTRY_USERNAME/python_app:v3"
      - echo "Build completed successfully!"

artifacts:
  files:
    - **/*.py
  discard-paths:
